name: g_sign_in
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0

flutter:

  uses-material-design: true
